KeyError at /accounts/register/
'password'
Request Method:	POST
Request URL:	http://127.0.0.1:8000/accounts/register/
Django Version:	5.2.2
Exception Type:	KeyError
Exception Value:	
'password'
Exception Location:	C:\Users\USER\Documents\Projects\Django\League App\League_app\users\forms.py, line 27, in clean_password2
Raised during:	users.views.register_view
Python Executable:	C:\Users\USER\AppData\Local\Programs\Python\Python313\python.exe
Python Version:	3.13.5
Python Path:	
['C:\\Users\\USER\\Documents\\Projects\\Django\\League App\\League_app',
 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip',
 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python313\\DLLs',
 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python313\\Lib',
 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python313',
 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages']
Server time:	Wed, 24 Sep 2025 21:18:09 +0000
Traceback Switch to copy-and-paste view
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\Documents\Projects\Django\League App\League_app\users\views.py, line 83, in register_view
        if form.is_valid():
               ^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\forms.py, line 206, in is_valid
        return self.is_bound and not self.errors
                                          ^^^^^^^^^^^ …
Local vars
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\forms.py, line 201, in errors
            self.full_clean()
                 ^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\forms.py, line 337, in full_clean
        self._clean_fields()
             ^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\forms.py, line 347, in _clean_fields
                    value = getattr(self, "clean_%s" % name)()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\USER\Documents\Projects\Django\League App\League_app\users\forms.py, line 27, in clean_password2
        if cd['password'] != cd['password2']: